runtime: python37
# env: standard
includes:
  - secret.yaml
service: default
entrypoint: gunicorn -b :$PORT main:app
handlers:
  - url: /static
    static_dir: flask_magne/static

  - url: /.*
    script: auto

automatic_scaling:
  target_cpu_utilization: 0.7 # default value is 0.6
  target_throughput_utilization: 0.7 # default value
  max_instances: 5
  min_instances: 0
  max_idle_instances: 1
  min_idle_instances: 0
  min_pending_latency: 3s # default value is 30ms
  max_pending_latency: 5s
  max_concurrent_requests: 80
